package com.jemyeonso.app.jemyeonsobe.common.enums;

import lombok.Getter;

@Getter
public enum ApiResponseCode {
    // 200 - 성공
    SUCCESS("SUCCESS"),
    TOKEN_REFRESH_SUCCESS("TOKEN_REFRESH_SUCCESS"),

    // 파일 관련 성공
    FILE_GET_SUCCESS("FILE_GET_SUCCESS"),
    FILE_LIST_SUCCESS("FILE_LIST_SUCCESS"),
    FILE_DELETE_SUCCESS("FILE_DELETE_SUCCESS"),

    // 면접 관련 성공
    INTERVIEW_LIST_GET_SUCCESS("INTERVIEW_LIST_GET_SUCCESS"),
    INTERVIEW_GET_SUCCESS("INTERVIEW_GET_SUCCESS"),
    INTERVIEW_DELETE_SUCCESS("INTERVIEW_DELETE_SUCCESS"),

    // 201 - 생성
    CREATED("CREATED"),

    // 400 - 잘못된 요청
    BAD_REQUEST("BAD_REQUEST"),
    INVALID_PARAMETER("INVALID_PARAMETER"),
    PAGINATION_INVALID_PARAMETER("PAGINATION_INVALID_PARAMETER"),

    // 401 - 인증 실패
    UNAUTHORIZED("UNAUTHORIZED"),

    // 403 - 권한 없음
    FORBIDDEN("FORBIDDEN"),
    FILE_ACCESS_DENIED("FILE_ACCESS_DENIED"),
    INTERVIEW_ACCESS_DENIED("INTERVIEW_ACCESS_DENIED"),

    // 404 - 찾을 수 없음
    NOT_FOUND("NOT_FOUND"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    INTERVIEW_NOT_FOUND("INTERVIEW_NOT_FOUND"),

    // 500 - 서버 오류
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    INTERNAL_ERROR("INTERNAL_ERROR"),

    // 기타
    MAX_UPLOAD_SIZE_EXCEEDED("MAX_UPLOAD_SIZE_EXCEEDED");

    private final String code;

    ApiResponseCode(String code) {
        this.code = code;
    }
}